env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[20666d7c19df0d3693c97c70b91d1abc9e5026aaa80c7248fd2d3968427bfbe72c1f02c23d64d1019793b2f0a653e457]"
  TG_TOKEN: "ENCRYPTED[2a1fbaeb13b5e93f4d23fcc86c3500132666ebbf387c4008f210f54da0ba7a52ddf65c57278bb68095fad316092a1c1e]"
  TG_CHAT_ID: "ENCRYPTED[9c75f5ed2411ffa3d6ce4d4fce10d3b7579fdb3ffb726b163dee2d71f8593c75324ec8ddab3c143ef4c1b83130f6cca3]"
  CREDENTIALS: "ENCRYPTED[bd43adaf960e8f12a812efe7992a54ed7d14b15ec34a6c99bb0279212417525c773871c8ee87c4cbb1e7afa4b729d7fa]"
  USER: "ENCRYPTED[54ec270619d18655190cc0b47289ebf8b8c68b713b5a48853914061d265c4227eaede263b425679c80bd703bfea4b4a1]"
  EMAIL: "ENCRYPTED[e30647a00596d21c65258f18a4ca12b3e58a7b1f9ec2b0625c585bf78786b309976e3d886e01e23709ad8b07bfa047af]"
  KBUILD_BUILD_USER: "ENCRYPTED[639f96fb06a1b1e1f626a8e0034047f4fa79013353159f61354b84e4cb6fde2f507f8b3739ecbb87fd1e918615987558]"
  KBUILD_BUILD_HOST: "ENCRYPTED[656c54cfc9753c91a99291b92d9c6276010355291b3d6797a1513d0eb6a373aecb949d3c38380b31035676648891d40d]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"
  
# TARGET
  APPS: "SystemUI"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'DeclanG9'
  timeout_in: 120m
  container:
    image: c3eru/gaspoll:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "$USER"
     - git config --global user.email "$EMAIL"
     - echo "$CREDENTIALS" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - export KBUILD_BUILD_USER=$KBUILD_BUILD_USER
     - export KBUILD_BUILD_HOST=$KBUILD_BUILD_USER
     - export BUILD_USERNAME=$KBUILD_BUILD_USER
     - export BUILD_HOSTNAME=$KBUILD_BUILD_USER


  Sinkronisasi_script:
     - ./script/sinkronisasi.sh
     
  Build-rom_script:
     - ./script/membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/mengunggah.sh
